baseURL = "https://iamtio.github.io/cv/"
defaultContentLanguage  = "en"
title = "Igor Tsarev CV"
# theme = ""
theme = "hugo-devresume-theme"
enableRobotsTXT  = true
# googleAnalytics = "UA-XXXXXXX-Y"
[params]
    author = "iamtio"
    description = "DevResume"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"
    [params.footer]
        copyright = "iamtio"

    [params.contact]
        enable = true
        location = "Espoo, Finland"

        # [[params.contact.list]]
        # icon = "fas fa-phone-square"
        # url = "tel:+79999735058"
        # text = "+7 999 973 50 58"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:9735058+cv@gmail.com"
        text = "9735058+cv@gmail.com"
    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Python/Django/DRF/Celery"
        [[params.skills.list.items]]
        details = "Rust"
        [[params.skills.list.items]]
        details = "JavaScript/React/CSS/SCSS"
        [[params.skills.list.items]]
        details = "Golang/Gin"
        [[params.skills.list.items]]
        details = "PostgreSQL/Redis"
        [[params.skills.list.items]]
        details = "Apache Kafka, RabbitMQ"
        [[params.skills.list.items]]
        details = "System architect/Microservices/SOA"
        [[params.skills.list.items]]
        details = "Well experienced in Kubernetes/Docker"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"

    [params.projects]
        enable = true
        [[params.projects.list]]
        title = "TRAWM"
        meta = "Rust, Embedded, BLE"
        tagline = "Firmware for RaspberryPi Pico 2040W with E-ink screen for displaying air quality metrics gathered from Airthings through Bluetooth LE"
        link = "https://github.com/iamtio/trawm"
        [[params.projects.list]]
        title = "GoRadex"
        meta = "Golang, Reverse enginering"
        tagline = "CLI tool for Quarta Radex One personal dosimeter"
        link = "https://github.com/iamtio/goradex"
        [[params.projects.list]]
        title = "OLED Gen"
        meta = "Golang, Arduino"
        tagline = "RAM/CPU usage real-time monitoring device. Arduino + 3D model for printing + PC side software"
        link = "https://github.com/iamtio/oledgen"
        [[params.projects.list]]
        title = "MQTT 2 Play"
        meta = "Golang, Smart home"
        tagline = '''Play sounds through MQTT'''
        link = "https://github.com/iamtio/mqtt2play"

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/iamtio"
        title = "iamtio"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/tsarevio"
        title = "tsarevio"
        [[params.social.list]]
        icon = "fab fa-stack-overflow"
        url = "//stackoverflow.com/users/1980388/tio"
        title = "tio"

[languages.ru.params]
    [languages.ru.params.summary]
        enable = true
        text = """IT-специалист с богатым опытом, как в роли FullStack разработчика так и в роли инженера интеграции.
         Являюсь активным сторонником OpenSource.
         В своей работе делаю активный уклон в сторону применения современных практик: Agile, DevOps, infrastructure as Code.
         Имею успешный опыт внедрения и эксплуатации Kubernetes, релизных политик.
         Нахожу общий язык с админами и QA
        """

    [languages.ru.params.profile]
        enable = true
        tagline = "DevOps/SRE engineer, Software Developer"
        avatar = "photo.jpg"
        name = "Царёв Игорь"
    [languages.ru.params.education]
        enable = true
        [[languages.ru.params.education.list]]
        degree = "Математическое обеспечение и администрирование информационных систем (02.03.03)"
        university = "Московский финансово-промышленный университет «Синергия»"
        dates = "2008 - 2013"
    [languages.ru.params.languages]
        enable = true
        [[languages.ru.params.languages.list]]
        name = "Русский"
        level = "Родной"
        [[languages.ru.params.languages.list]]
        name = "Английский"
        level = "Срединй"
    [languages.ru.params.interests]
        enable = true
        [[languages.ru.params.interests.list]]
        name = "PC/VR гейминг"
        [[languages.ru.params.interests.list]]
        name = "Умный дом/интернет вещей"
        [[languages.ru.params.interests.list]]
        name = "Путешествия"
    [languages.ru.params.experience]
        enable = true

        [[languages.ru.params.experience.list]]
        company = "Самолет девелопмент"
        title = "Руководитель группы"
        dates = "01.2021 - 05.2022"
        details = "Выполнял обязанности руководителя DevOps инженеров, и Backend разработчиков в группе разработки сервисов"
        [[languages.ru.params.experience.list.items]]
        details = "Code Review, архитектурный надзор"
        [[languages.ru.params.experience.list.items]]
        details = "Коммуникации с сис. админам по вопросам развития инфруструктуры"
        [[languages.ru.params.experience.list.items]]
        details = "Применение Agile/Scrum/Kanban методологий"
        [[languages.ru.params.experience.list.items]]
        details = "Приоритезация задач и планирование"
        [[languages.ru.params.experience.list.items]]
        details = "Успешное внедрение Docker, Kubernetes, Gitlab, включая практики CI/CD"
        [[languages.ru.params.experience.list.items]]
        details = "Настройка Prometheus, Grafana, Alert Manager. Сбор метрик, создание дашбородов, правил алертинга"
        [[languages.ru.params.experience.list.items]]
        details = "Разработка микросервисов на Python/Go"
        
        [[languages.ru.params.experience.list]]
        company = "Самолет девелопмент"
        title = "Ведущий разрабочик"
        dates = "05.2019 - 01.2021"
        details = "Fullstack разработка (Python/Django, JavaScript/ReactJS, Golang) и проектирование"
        [[languages.ru.params.experience.list.items]]
        details = "Разработка проектов автоматизации BIM"
        [[languages.ru.params.experience.list.items]]
        details = "Проектирование и разработка системных сервисов. Включая модуль SSO (Single Sign On)"
        [[languages.ru.params.experience.list.items]]
        details = "Успешно внедрил Apache Kafka, как событийную шину в компании"
        [[languages.ru.params.experience.list.items]]
        details = "Внедрение DevOps практик в компании"

        [[languages.ru.params.experience.list]]
        company = "Поисковый портал Спутник"
        title = "Старший разработчик направления"
        dates = "09.2014 - 05.2019"
        details = "Fullstack разработка (Python/Django, JavaScript/AngularJS)"
        [[languages.ru.params.experience.list.items]]
        details = "Запуск в эксплуатацию и доработка B2B системы IoT (Golang, PostgreSQL, GRPC, Kubernetes)"
        [[languages.ru.params.experience.list.items]]
        details = "Проектирование и разработка системы оценки качества поиска (Django, DRF, AngularJS, Celery)"
        [[languages.ru.params.experience.list.items]]
        details = "JS Плагин для FireFox для работы сотрудников (Bootstrap, AngularJS, Firefox SDK)"
        [[languages.ru.params.experience.list.items]]
        details = "Разработка системы голосования сотрудников (Django, DRF, AngularJS)"
        [[languages.ru.params.experience.list.items]]
        details = "Интеграция Django с HDFS, Hadoop, MapReduce задачами"
        [[languages.ru.params.experience.list.items]]
        details = "Разработка различных корпоративных админок (AngularJS, Django)"

        [[languages.ru.params.experience.list]]
        company = "Интернет магизин VZV"
        title = "Backend разработчик"
        dates = "12.2013 - 09.2014"
        details = "Perl, Python, PostgreSQL"
        [[languages.ru.params.experience.list.items]]
        details = "Внедрение подхода SPA (Single Page Application)"
        [[languages.ru.params.experience.list.items]]
        details = "Создание RESTFul API(Perl, Python)"
        [[languages.ru.params.experience.list.items]]
        details = "Автоматизация создания различных отчётов (xls, rtf, html)"
        [[languages.ru.params.experience.list.items]]
        details = "Внедрение GIT, Ansible"
        [[languages.ru.params.experience.list.items]]
        details = "Коммуникации с сис. админам"
        [[languages.ru.params.experience.list.items]]
        details = "Формирование, деплой релизов и их согласование с менеджментом"
        [[languages.ru.params.experience.list.items]]
        details = "Различные интеграции, включая 1С"

        [[languages.ru.params.experience.list]]
        company = "SMS-Online"
        title = "Backend разработчик"
        dates = "12.2013 - 09.2014"
        details = "Perl, Java, C"
        [[languages.ru.params.experience.list.items]]
        details = "Разработка мониторинга продуктовых метрик(Perl, Zabbix)"
        [[languages.ru.params.experience.list.items]]
        details = "Разработка ядра систмемы СМС-Шлюза(Perl, PostgreSQL, Redis)"
        [[languages.ru.params.experience.list.items]]
        details = "Интеграция платформы СМС-Шлаюза с API операторов (Perl, Java)"
        [[languages.ru.params.experience.list.items]]
        details = "Дежурство и оперативное решение проблем в продакшен-среде"
        
[languages.en.params]
    [languages.en.params.summary]
        enable = true
        text = """
         Well experienced IT-Engineer as a FullStack developer and also as a software integration engineer.
         Active OpenSource supporter/participant.
         In my work I am paying attention to applying modern practicies, such as Agile, DevOps, Infrastructure as Code.
         Having successful experience in introducting and using Kubernetes, software release policies.
         Good in finding common grounds with Ops and QA
        """
    [languages.en.params.profile]
        enable = true
        tagline = "DevOps/SRE engineer, Software Developer"
        avatar = "photo.jpg"    
        name = "Igor Tsarev"
    [languages.en.params.education]
        enable = true
        [[languages.en.params.education.list]]
        degree = "B.Sc., Computer Science"
        university = "Moscow University for Industry and Finance «Synergy»"
        dates = "2008 - 2013"
    [languages.en.params.languages]
        enable = true
        [[languages.en.params.languages.list]]
        name = "Russian"
        level = "Native"
        [[languages.en.params.languages.list]]
        name = "English"
        level = "Intermediate"

    [languages.en.params.interests]
        enable = true

        [[languages.en.params.interests.list]]
        name = "PC/VR Gaming"
        [[languages.en.params.interests.list]]
        name = "SmartHome/IOT enthusiast"
        [[languages.en.params.interests.list]]
        name = "Travelling"
    [languages.en.params.experience]
        enable = true

        [[languages.en.params.experience.list]]
        company = "Samolet development"
        title = "Team Lead"
        dates = "01.2021 - 05.2022"
        details = "Leading DevOps Engineers and Backend(Python) developers"
        [[languages.en.params.experience.list.items]]
        details = "Code Review, architecure supervising"
        [[languages.en.params.experience.list.items]]
        details = "Infrustucture improvements communication with Ops"
        [[languages.en.params.experience.list.items]]
        details = "Applying Agile/Kanban frameworks"
        [[languages.en.params.experience.list.items]]
        details = "Team planning and issues prioritization"
        [[languages.en.params.experience.list.items]]
        details = "Successfully applying Docker, Kubernetes, Gitlab in dev/staging/productions environments"
        [[languages.en.params.experience.list.items]]
        details = "Supporting of Prometheus, Grafana, Alert Manager. Metrics scraping, creating new dashboards, making alert rules"
        [[languages.en.params.experience.list.items]]
        details = "Developing microservices using Python/GoLang"
        
        [[languages.en.params.experience.list]]
        company = "Samolet development"
        title = "Senior Developer"
        dates = "05.2019 - 01.2021"
        details = "Fullstack development (Python/Django, JavaScript/ReactJS, Golang) and architecture design"
        [[languages.en.params.experience.list.items]]
        details = "Developing automation projects for BIM (Building Information Model)"
        [[languages.en.params.experience.list.items]]
        details = "Software design and developing of system services. Including SSO (Singe Sign On)"
        [[languages.en.params.experience.list.items]]
        details = "Successfully introduced Apache Kafka, as event-driven bus for whole company"
        [[languages.en.params.experience.list.items]]
        details = "Introducing DevOps practices into dev teams"

        [[languages.en.params.experience.list]]
        company = "Search portal Sputnik"
        title = "Senior developer"
        dates = "09.2014 - 05.2019"
        details = "Fullstack development (Python/Django, JavaScript/AngularJS)"
        [[languages.en.params.experience.list.items]]
        details = "Code revision and putting into operation B2B IoT platform (Golang, PostgreSQL, GRPC, Kubernetes)"
        [[languages.en.params.experience.list.items]]
        details = "Software design and developing of search quality scoring system (Django, DRF, AngularJS, Celery)"
        [[languages.en.params.experience.list.items]]
        details = "Developed corporate JavaScript Addon for Firefox for employees and partners (Bootstrap, AngularJS, Firefox SDK)"
        [[languages.en.params.experience.list.items]]
        details = "Developed corporate voting system for employees (Django, DRF, AngularJS)"
        [[languages.en.params.experience.list.items]]
        details = "Django integration with HDFS, Hadoop, MapReduce tasks"
        [[languages.en.params.experience.list.items]]
        details = "Developed a lot of various corporate admin dashbards (AngularJS, Django)"

        [[languages.en.params.experience.list]]
        company = "Internet shop VZV"
        title = "Backend developer"
        dates = "12.2013 - 09.2014"
        details = "Perl, Python, PostgreSQL"
        [[languages.en.params.experience.list.items]]
        details = "Introducing and applying SPA (Single Page Application)"
        [[languages.en.params.experience.list.items]]
        details = "Creaing RESTFul APIs(Perl, Python) for frontend developers"
        [[languages.en.params.experience.list.items]]
        details = "Various reports automantion(xls, rtf, html)"
        [[languages.en.params.experience.list.items]]
        details = "Using of GIT, Ansible"
        [[languages.en.params.experience.list.items]]
        details = "Ops (Infrstructure) communication"
        [[languages.en.params.experience.list.items]]
        details = "Software releases coordination and deployment"
        [[languages.en.params.experience.list.items]]
        details = "Various integrations, including 1C:Enterprise"

        [[languages.en.params.experience.list]]
        company = "SMS-Online"
        title = "Backend developer"
        dates = "12.2013 - 09.2014"
        details = "Perl, Java, C"
        [[languages.en.params.experience.list.items]]
        details = "Creation of bussiness monitoring rules(Perl, Zabbix)"
        [[languages.en.params.experience.list.items]]
        details = "SMS-Gate core developing(Perl, PostgreSQL, Redis)"
        [[languages.en.params.experience.list.items]]
        details = "SMS-Gate integrations with mobile network operators (Perl, Java)"
        [[languages.en.params.experience.list.items]]
        details = "Regular duties and hotfixing issues in production environment" # !!!