# baseURL = 'http://example.org/'
# languageCode = 'en-us'
# title = 'My New Hugo Site'
# theme = 'hugo-devresume-theme'
# [params.footer]
#     copyright = ""

# Page settings

baseURL = "http://example.org/"
defaultContentLanguage  = "ru"
# languageCode = "ru"
title = ""
theme = "hugo-devresume-theme"
# googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "iamtio"
    description = "DevResume"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"
    [params.footer]
        copyright = "iamtio"

    [params.contact]
        enable = true
        location = "Moscow, Russia"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:+79999735058"
        text = "+7 999 973 50 58"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:9735058+cv@gmail.com"
        text = "9735058+cv@gmail.com"
    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Python/Django/DRF/Celery"
        [[params.skills.list.items]]
        details = "Golang/Gin"
        [[params.skills.list.items]]
        details = "JavaScript/React/CSS/SCSS"
        [[params.skills.list.items]]
        details = "PostgreSQL/Redis"
        [[params.skills.list.items]]
        details = "System architect/Microservices/SOA"
        [[params.skills.list.items]]
        details = "Well experienced in Kubernetes/Docker"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"

    [params.experience]
        enable = true

        [[params.experience.list]]
        company = "Самолет деволпмент"
        title = "Руководитель группы"
        dates = "01.2021 - настоящее время"
        details = "Выполнял обязанности руководителя DevOps инженеров, и Backend разработчиков в группе разработки сервисов"
        [[params.experience.list.items]]
        details = "Управление командой DevOps инженеров и разработчиков"
        [[params.experience.list.items]]
        details = "Коммуникации с сис. админам по вопросам развития инфруструктуры"
        [[params.experience.list.items]]
        details = "Применение Agile/Scrum/Kanban методологий"
        [[params.experience.list.items]]
        details = "Приоритезация задач и планирование"
        [[params.experience.list.items]]
        details = "Внедрение и интеграция программных продуктов компании"
        [[params.experience.list.items]]
        details = "Успешное внедрение Docker, Kubernetes, Gitlab, включая практики CI/CD"
        [[params.experience.list.items]]
        details = "Настройка Prometheus, Grafana, Alert Manager. Сбор метрик, создание дашбородов, правил алертинга"
        [[params.experience.list.items]]
        details = "Разработка микросервисов на Python/Go"
        
        [[params.experience.list]]
        company = "Самолет деволпмент"
        title = "Ведущий разрабочик"
        dates = "05.2019 - 01.2021"
        details = "Fullstack разработка (Python/Django, JavaScript/ReactJS, Golang) и проектирование"
        [[params.experience.list.items]]
        details = "Разработка проектов автоматизации BIM"
        [[params.experience.list.items]]
        details = "Проектирование и разработка системных сервисов. Включая модуль SSO (Single Sign On)"
        [[params.experience.list.items]]
        details = "Успешно внедрил Apache Kafka, как событийную шину в компании"
        [[params.experience.list.items]]
        details = "Внедрение DevOps практик в компании"

        [[params.experience.list]]
        company = "Поисковый портал Спутник"
        title = "Старший разработчик направления"
        dates = "09.2014 - 05.2019"
        details = "Fullstack разработка (Python/Django, JavaScript/AngularJS)"
        [[params.experience.list.items]]
        details = "Запуск в эксплуатациюи доработка B2B системы IoT (Golang, PostgreSQL, GRPC, Kubernetes)"
        [[params.experience.list.items]]
        details = "Проектирование и разработка системы оценки качества поиска (Django, DRF, AngularJS, Celery)"
        [[params.experience.list.items]]
        details = "JS Плагин для FireFox для работы сотрудников (Bootstrap, AngularJS, Firefox SDK)"
        [[params.experience.list.items]]
        details = "Разработка системы голосования сотрудников (Django, DRF, AngularJS)"
        [[params.experience.list.items]]
        details = "Интеграция Django с HDFS, Hadoop, MapReduce задачами"
        [[params.experience.list.items]]
        details = "Разработка различных корпоративных админок(AngularJS, Django)"

        [[params.experience.list]]
        company = "Интернет магизин VZV"
        title = "Backend разработчик"
        dates = "12.2013 - 09.2014"
        details = "Perl, Python, PostgreSQL"
        [[params.experience.list.items]]
        details = "Внедрение подхода SPA (Single Page Application)"
        [[params.experience.list.items]]
        details = "Создание RESTFul API(Perl, Python)"
        [[params.experience.list.items]]
        details = "Автоматизация создания различных отчётов (xls, rtf, html)"
        [[params.experience.list.items]]
        details = "Внедрение GIT, Ansible"
        [[params.experience.list.items]]
        details = "Коммуникации с сис. админам"
        [[params.experience.list.items]]
        details = "Формирование, деплой релизов и их согласование с менеджментом"
        [[params.experience.list.items]]
        details = "Различные интеграции, включая 1С"

        [[params.experience.list]]
        company = "SMS-Online"
        title = "Backend разработчик"
        dates = "12.2013 - 09.2014"
        details = "Perl, Java, C"
        [[params.experience.list.items]]
        details = "Разработка мониторинга продуктовых метрик(Perl, Zabbix)"
        [[params.experience.list.items]]
        details = "Разработка ядра систмемы СМС-Шлюза(Perl, PostgreSQL, Redis)"
        [[params.experience.list.items]]
        details = "Интеграция платформы СМС-Шлаюза с API операторов (Perl, Java)"
        [[params.experience.list.items]]
        details = "Дежурство и оперативное решение проблем в продакшен-среде"

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "OLED Gen"
        meta = "Open Source"
        tagline = "RAM/CPU usage real-time monitoring device. Arduino + 3D model for printing + PC side software (Golang)"
        link = "https://github.com/iamtio/oledgen"
        [[params.projects.list]]
        title = "MQTT 2 Play"
        meta = "Open Source"
        tagline = '''Play sounds through MQTT (Golang)'''
        link = "https://github.com/iamtio/mqtt2play"

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/iamtio"
        title = "iamtio"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/tsarevio"
        title = "tsarevio"
        [[params.social.list]]
        icon = "fab fa-stack-overflow"
        url = "//stackoverflow.com/users/1980388/tio"
        title = "tio"

[languages.ru.params]
    [languages.ru.params.summary]
        enable = true
        text = """IT-специалист с богатым опытом, как в роли FullStack разработчика так и в роли инженера интеграции.
         Являюсь активным сторонником OpenSource.
         В своей работе делаю активный уклон в сторону применения современных практик: Agile, DevOps, infrastructure as Code.
         Имею успешный опыт внедрения и эксплатации Kubernetes, релизных политик.
         Нахожу общий язык с админами и QA
        """

    [languages.ru.params.profile]
        enable = true
        tagline = "DevOps/SRE engineer, Software Developer"
        avatar = "photo.jpg"
        name = "Царёв Игорь"
    [languages.ru.params.education]
        enable = true
        [[languages.ru.params.education.list]]
        degree = "Математическое обеспечение и администрирование информационных систем (02.03.03)"
        university = "Московский финансово-промышленный университет «Синергия»"
        dates = "2008 - 2013"
    [languages.ru.params.languages]
        enable = true
        [[languages.ru.params.languages.list]]
        name = "Русский"
        level = "Родной"
        [[languages.ru.params.languages.list]]
        name = "Английский"
        level = "Срединй"
    [languages.ru.params.interests]
        enable = true
        [[languages.ru.params.interests.list]]
        name = "PC/VR гейминг"
        [[languages.ru.params.interests.list]]
        name = "Умный дом/интернет вещей"
        [[languages.ru.params.interests.list]]
        name = "Путешествия"
[languages.en.params]
    [languages.en.params.summary]
        enable = true
        text = """
         Well experienced IT-Engineer as FullStack developer and also software integration engineer.
         Active OpenSource supporter/participant.
         In my work I am paying attention to applying modern practicies, such as Agile, DevOps, Infrastructure as Code.
         Having successful experience in introducting and using Kubernetes, software release policies.
         Good in finding common grounds with Ops and QA
        """
    [languages.en.params.profile]
        enable = true
        tagline = "DevOps/SRE engineer, Software Developer"
        avatar = "photo.jpg"    
        name = "Igor Tsarev"
    [languages.en.params.education]
        enable = true
        [[languages.en.params.education.list]]
        degree = "B.Sc., Computer Science"
        university = "Moscow University for Industry and Finance «Synergy»"
        dates = "2008 - 2013"
    [languages.en.params.languages]
        enable = true
        [[languages.en.params.languages.list]]
        name = "Russian"
        level = "Native"
        [[languages.en.params.languages.list]]
        name = "English"
        level = "Intermediate"

    [languages.en.params.interests]
        enable = true

        [[languages.en.params.interests.list]]
        name = "PC/VR Gaming"
        [[languages.en.params.interests.list]]
        name = "SmartHome/IOT enthusiast"
        [[languages.en.params.interests.list]]
        name = "Travelling"
